config/routes.rb
Inventorysolution::Application.routes.draw do
  break if ARGV.join.include? ‘assets:precompile’
  
  root :to => "home#index"

  resources :bincontents

  resources :storagebins

  resources :warehouselocations

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :suppliers

  resources :products

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bincontent.rb
class Bincontent < ActiveRecord::Base
  attr_accessible :product_id, :productexpirationdate, :quantify, :reorderquantity, :storagebin_id, :unitofmeasure

  belongs_to :storagebins , :class_name => "Storagebin", :foreign_key => "storagebin_id"
 # has_many :products, class_name => "Product", :foreign_key => "product_id"
  belongs_to :products, :class_name => "Product", :foreign_key => "product_id"

 
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :deliveryleadtime, :firstitemsupplieddate, :lastitemsupplieddate, :maximumorderquantity, :minimumorderquantity, :percentagediscount, :productdescription, :productname, :quantitytype, :standardprice, :supplier_id, :totalquantitysuppliedtodate, :valuesuppliedtodate

 belongs_to :suppliers , :class_name => "Supplier", :foreign_key => "supplier_id"
 has_many :bincontents

end

app/models/storagebin.rb
class Storagebin < ActiveRecord::Base
  attr_accessible :level_z, :row_x, :stack_y, :storagebinname, :warehouselocation_id

  has_many :bincontents
  belongs_to :warehouselocations , :class_name => "Warehouselocation", :foreign_key => "warehouselocation_id"
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  attr_accessible :building, :city, :contactperson, :country, :email1, :email2, :fax, :mobile, :phone1, :phone2, :street, :suppliername, :website, :zip

  has_many :products
end

app/models/warehouselocation.rb
class Warehouselocation < ActiveRecord::Base
  attr_accessible :city, :contactperson, :country, :email, :mobile, :number, :phone, :street, :warehousename, :zip

  has_many :storagebins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/bincontents_controller.rb
class BincontentsController < InheritedResources::Base
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
     
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/storagebins_controller.rb
class StoragebinsController < InheritedResources::Base
	
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  
  # GET /suppliers
  # GET /suppliers.json
  def index
    @suppliers = Supplier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suppliers }
    end
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @supplier }
    end
  end

  # GET /suppliers/new
  # GET /suppliers/new.json
  def new
    @supplier = Supplier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @supplier }
    end
  end

  # GET /suppliers/1/edit
  def edit
    @supplier = Supplier.find(params[:id])
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    @supplier = Supplier.new(params[:supplier])

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: 'Supplier was successfully created.' }
        format.json { render json: @supplier, status: :created, location: @supplier }
      else
        format.html { render action: "new" }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suppliers/1
  # PUT /suppliers/1.json
  def update
    @supplier = Supplier.find(params[:id])

    respond_to do |format|
      if @supplier.update_attributes(params[:supplier])
        format.html { redirect_to @supplier, notice: 'Supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy

    respond_to do |format|
      format.html { redirect_to suppliers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/warehouselocations_controller.rb
class WarehouselocationsController < InheritedResources::Base
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bincontents_helper.rb
module BincontentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_imports_controller_helper.rb
module ProductImportsControllerHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storagebins_helper.rb
module StoragebinsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/warehouselocations_helper.rb
module WarehouselocationsHelper
end

app/views/bincontents/_form.html.erb
<%= form_for(@bincontent) do |f| %>
  <% if @bincontent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bincontent.errors.count, "error") %> prohibited this bincontent from being saved:</h2>

      <ul>
      <% @bincontent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :storagebin_id %><br />
    <%= f.number_field :storagebin_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :unitofmeasure %><br />
    <%= f.text_field :unitofmeasure %>
  </div>
  <div class="field">
    <%= f.label :quantify %><br />
    <%= f.text_field :quantify %>
  </div>
  <div class="field">
    <%= f.label :reorderquantity %><br />
    <%= f.text_field :reorderquantity %>
  </div>
  <div class="field">
    <%= f.label :productexpirationdate %><br />
    <%= f.date_select :productexpirationdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bincontents/edit.html.erb
<h1>Editing bincontent</h1>

<%= render 'form' %>

<%= link_to 'Show', @bincontent %> |
<%= link_to 'Back', bincontents_path %>

app/views/bincontents/index.html.erb
<h1>Listing bincontents</h1>

<table>
  <tr>
    <th>Storagebin</th>
    <th>Product</th>
    <th>Unitofmeasure</th>
    <th>Quantify</th>
    <th>Reorderquantity</th>
    <th>Productexpirationdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bincontents.each do |bincontent| %>
  <tr>
    <td><%= bincontent.storagebin_id %></td>
    <td><%= bincontent.product_id %></td>
    <td><%= bincontent.unitofmeasure %></td>
    <td><%= bincontent.quantify %></td>
    <td><%= bincontent.reorderquantity %></td>
    <td><%= bincontent.productexpirationdate %></td>
    <td><%= link_to 'Show', bincontent %></td>
    <td><%= link_to 'Edit', edit_bincontent_path(bincontent) %></td>
    <td><%= link_to 'Destroy', bincontent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bincontent', new_bincontent_path %>

app/views/bincontents/new.html.erb
<h1>New bincontent</h1>

<%= render 'form' %>

<%= link_to 'Back', bincontents_path %>

app/views/bincontents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Storagebin:</b>
  <%= @bincontent.storagebin_id %>
</p>

<p>
  <b>Product:</b>
  <%= @bincontent.product_id %>
</p>

<p>
  <b>Unitofmeasure:</b>
  <%= @bincontent.unitofmeasure %>
</p>

<p>
  <b>Quantify:</b>
  <%= @bincontent.quantify %>
</p>

<p>
  <b>Reorderquantity:</b>
  <%= @bincontent.reorderquantity %>
</p>

<p>
  <b>Productexpirationdate:</b>
  <%= @bincontent.productexpirationdate %>
</p>


<%= link_to 'Edit', edit_bincontent_path(@bincontent) %> |
<%= link_to 'Back', bincontents_path %>

app/views/home/index.html.erb
<h1>Inventory Solution</h1>
<p>Please login <%= link_to 'HERE', admin_dashboard_path %></p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--
  <div class="field">
    <%= f.label :productname %><br />
    <%= f.text_field :productname %>
  </div>

-->
  <div class="field">
    <%= f.label :supplier_id %><br />
    <!-- %= f.number_field :supplier_id % -->
    <%= f.input :supplier, :label => 'Supplier', :as => :select => proc {(Supplier.all).map{|c| [c.suppliername, c.id] }} :include_blank => false % %>
  </div>
  <div class="field">
    <%= f.label :productdescription %><br />
    <%= f.text_field :productdescription %>
  </div>
  <div class="field">
    <%= f.label :standardprice %><br />
    <%= f.text_field :standardprice %>
  </div>
  <div class="field">
    <%= f.label :minimumorderquantity %><br />
    <%= f.number_field :minimumorderquantity %>
  </div>
  <div class="field">
    <%= f.label :maximumorderquantity %><br />
    <%= f.text_field :maximumorderquantity %>
  </div>
  <div class="field">
    <%= f.label :quantitytype %><br />
    <%= f.text_field :quantitytype %>
  </div>
  <div class="field">
    <%= f.label :deliveryleadtime %><br />
    <%= f.number_field :deliveryleadtime %>
  </div>
  <div class="field">
    <%= f.label :valuesuppliedtodate %><br />
    <%= f.text_field :valuesuppliedtodate %>
  </div>
  <div class="field">
    <%= f.label :totalquantitysuppliedtodate %><br />
    <%= f.number_field :totalquantitysuppliedtodate %>
  </div>
  <div class="field">
    <%= f.label :firstitemsupplieddate %><br />
    <%= f.date_select :firstitemsupplieddate %>
  </div>
  <div class="field">
    <%= f.label :lastitemsupplieddate %><br />
    <%= f.date_select :lastitemsupplieddate %>
  </div>
  <div class="field">
    <%= f.label :percentagediscount %><br />
    <%= f.number_field :percentagediscount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>


<table>
  <tr>
    <th>Productname</th>
    <th>Supplier</th>
    <th>Productdescription</th>
    <th>Standardprice</th>
    <th>Minimumorderquantity</th>
    <th>Maximumorderquantity</th>
    <th>Quantitytype</th>
    <th>Deliveryleadtime</th>
    <th>Valuesuppliedtodate</th>
    <th>Totalquantitysuppliedtodate</th>
    <th>Firstitemsupplieddate</th>
    <th>Lastitemsupplieddate</th>
    <th>Percentagediscount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.productname %></td>
    <td><%= product.supplier_id %></td>
    <td><%= product.productdescription %></td>
    <td><%= product.standardprice %></td>
    <td><%= product.minimumorderquantity %></td>
    <td><%= product.maximumorderquantity %></td>
    <td><%= product.quantitytype %></td>
    <td><%= product.deliveryleadtime %></td>
    <td><%= product.valuesuppliedtodate %></td>
    <td><%= product.totalquantitysuppliedtodate %></td>
    <td><%= product.firstitemsupplieddate %></td>
    <td><%= product.lastitemsupplieddate %></td>
    <td><%= product.percentagediscount %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Productname:</b>
  <%= @product.productname %>
</p>

<p>
  <b>Supplier:</b>
  <%= @product.supplier_id %>
</p>

<p>
  <b>Productdescription:</b>
  <%= @product.productdescription %>
</p>

<p>
  <b>Standardprice:</b>
  <%= @product.standardprice %>
</p>

<p>
  <b>Minimumorderquantity:</b>
  <%= @product.minimumorderquantity %>
</p>

<p>
  <b>Maximumorderquantity:</b>
  <%= @product.maximumorderquantity %>
</p>

<p>
  <b>Quantitytype:</b>
  <%= @product.quantitytype %>
</p>

<p>
  <b>Deliveryleadtime:</b>
  <%= @product.deliveryleadtime %>
</p>

<p>
  <b>Valuesuppliedtodate:</b>
  <%= @product.valuesuppliedtodate %>
</p>

<p>
  <b>Totalquantitysuppliedtodate:</b>
  <%= @product.totalquantitysuppliedtodate %>
</p>

<p>
  <b>Firstitemsupplieddate:</b>
  <%= @product.firstitemsupplieddate %>
</p>

<p>
  <b>Lastitemsupplieddate:</b>
  <%= @product.lastitemsupplieddate %>
</p>

<p>
  <b>Percentagediscount:</b>
  <%= @product.percentagediscount %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storagebins/_form.html.erb
<%= form_for(@storagebin) do |f| %>
  <% if @storagebin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@storagebin.errors.count, "error") %> prohibited this storagebin from being saved:</h2>

      <ul>
      <% @storagebin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :warehouselocation_id %><br />
    <!-- %= f.number_field :warehouselocation_id % -->
    <%= f.input :warehouselocation_id, :as => :select, :collection => Hash[Warehouselocation.all.map{|b| [b.warehousename,b.id]}] %>
  </div>
  <div class="field">
    <%= f.label :storagebinname %><br />
    <%= f.text_field :storagebinname %>
  </div>
  <div class="field">
    <%= f.label :row_x %><br />
    <%= f.number_field :row_x %>
  </div>
  <div class="field">
    <%= f.label :stack_y %><br />
    <%= f.number_field :stack_y %>
  </div>
  <div class="field">
    <%= f.label :level_z %><br />
    <%= f.number_field :level_z %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/storagebins/edit.html.erb
<h1>Editing storagebin</h1>

<%= render 'form' %>

<%= link_to 'Show', @storagebin %> |
<%= link_to 'Back', storagebins_path %>

app/views/storagebins/index.html.erb
<h1>Listing storagebins</h1>

<table>
  <tr>
    <th>Warehouselocation</th>
    <th>Storagebinname</th>
    <th>Row x</th>
    <th>Stack y</th>
    <th>Level z</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @storagebins.each do |storagebin| %>
  <tr>
    <td><%= storagebin.warehouselocation_id %></td>
    <td><%= storagebin.storagebinname %></td>
    <td><%= storagebin.row_x %></td>
    <td><%= storagebin.stack_y %></td>
    <td><%= storagebin.level_z %></td>
    <td><%= link_to 'Show', storagebin %></td>
    <td><%= link_to 'Edit', edit_storagebin_path(storagebin) %></td>
    <td><%= link_to 'Destroy', storagebin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Storagebin', new_storagebin_path %>

app/views/storagebins/new.html.erb
<h1>New storagebin</h1>

<%= render 'form' %>

<%= link_to 'Back', storagebins_path %>

app/views/storagebins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Warehouselocation:</b>
  <%= @storagebin.warehouselocation_id %>
</p>

<p>
  <b>Storagebinname:</b>
  <%= @storagebin.storagebinname %>
</p>

<p>
  <b>Row x:</b>
  <%= @storagebin.row_x %>
</p>

<p>
  <b>Stack y:</b>
  <%= @storagebin.stack_y %>
</p>

<p>
  <b>Level z:</b>
  <%= @storagebin.level_z %>
</p>


<%= link_to 'Edit', edit_storagebin_path(@storagebin) %> |
<%= link_to 'Back', storagebins_path %>

app/views/suppliers/_form.html.erb
<%= form_for(@supplier) do |f| %>
  <% if @supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :suppliername %><br />
    <%= f.text_field :suppliername %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :building %><br />
    <%= f.text_field :building %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :contactperson %><br />
    <%= f.text_field :contactperson %>
  </div>
  <div class="field">
    <%= f.label :phone1 %><br />
    <%= f.text_field :phone1 %>
  </div>
  <div class="field">
    <%= f.label :phone2 %><br />
    <%= f.text_field :phone2 %>
  </div>
  <div class="field">
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email1 %><br />
    <%= f.text_field :email1 %>
  </div>
  <div class="field">
    <%= f.label :email2 %><br />
    <%= f.text_field :email2 %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @supplier %> |
<%= link_to 'Back', suppliers_path %>

app/views/suppliers/index.html.erb
<h1>Listing suppliers</h1>

<table>
  <tr>
    <th>Suppliername</th>
    <th>Street</th>
    <th>Building</th>
    <th>Zip</th>
    <th>City</th>
    <th>Country</th>
    <th>Contactperson</th>
    <th>Phone1</th>
    <th>Phone2</th>
    <th>Fax</th>
    <th>Mobile</th>
    <th>Email1</th>
    <th>Email2</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suppliers.each do |supplier| %>
  <tr>
    <td><%= supplier.suppliername %></td>
    <td><%= supplier.street %></td>
    <td><%= supplier.building %></td>
    <td><%= supplier.zip %></td>
    <td><%= supplier.city %></td>
    <td><%= supplier.country %></td>
    <td><%= supplier.contactperson %></td>
    <td><%= supplier.phone1 %></td>
    <td><%= supplier.phone2 %></td>
    <td><%= supplier.fax %></td>
    <td><%= supplier.mobile %></td>
    <td><%= supplier.email1 %></td>
    <td><%= supplier.email2 %></td>
    <td><%= supplier.website %></td>
    <td><%= link_to 'Show', supplier %></td>
    <td><%= link_to 'Edit', edit_supplier_path(supplier) %></td>
    <td><%= link_to 'Destroy', supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Supplier', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New supplier</h1>

<%= render 'form' %>

<%= link_to 'Back', suppliers_path %>

app/views/suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Suppliername:</b>
  <%= @supplier.suppliername %>
</p>

<p>
  <b>Street:</b>
  <%= @supplier.street %>
</p>

<p>
  <b>Building:</b>
  <%= @supplier.building %>
</p>

<p>
  <b>Zip:</b>
  <%= @supplier.zip %>
</p>

<p>
  <b>City:</b>
  <%= @supplier.city %>
</p>

<p>
  <b>Country:</b>
  <%= @supplier.country %>
</p>

<p>
  <b>Contactperson:</b>
  <%= @supplier.contactperson %>
</p>

<p>
  <b>Phone1:</b>
  <%= @supplier.phone1 %>
</p>

<p>
  <b>Phone2:</b>
  <%= @supplier.phone2 %>
</p>

<p>
  <b>Fax:</b>
  <%= @supplier.fax %>
</p>

<p>
  <b>Mobile:</b>
  <%= @supplier.mobile %>
</p>

<p>
  <b>Email1:</b>
  <%= @supplier.email1 %>
</p>

<p>
  <b>Email2:</b>
  <%= @supplier.email2 %>
</p>

<p>
  <b>Website:</b>
  <%= @supplier.website %>
</p>


<%= link_to 'Edit', edit_supplier_path(@supplier) %> |
<%= link_to 'Back', suppliers_path %>

app/views/warehouselocations/edit.html.erb
<h1>Editing warehouselocation</h1>

<%= render 'form' %>

<%= link_to 'Show', @warehouselocation %> |
<%= link_to 'Back', warehouselocations_path %>

app/views/warehouselocations/index.html.erb
<h1>Listing warehouselocations</h1>

<table>
  <tr>
    <th>Warehousename</th>
    <th>Street</th>
    <th>Number</th>
    <th>Zip</th>
    <th>City</th>
    <th>Country</th>
    <th>Contactperson</th>
    <th>Phone</th>
    <th>Mobile</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @warehouselocations.each do |warehouselocation| %>
  <tr>
    <td><%= warehouselocation.warehousename %></td>
    <td><%= warehouselocation.street %></td>
    <td><%= warehouselocation.number %></td>
    <td><%= warehouselocation.zip %></td>
    <td><%= warehouselocation.city %></td>
    <td><%= warehouselocation.country %></td>
    <td><%= warehouselocation.contactperson %></td>
    <td><%= warehouselocation.phone %></td>
    <td><%= warehouselocation.mobile %></td>
    <td><%= warehouselocation.email %></td>
    <td><%= link_to 'Show', warehouselocation %></td>
    <td><%= link_to 'Edit', edit_warehouselocation_path(warehouselocation) %></td>
    <td><%= link_to 'Destroy', warehouselocation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Warehouselocation', new_warehouselocation_path %>

app/views/warehouselocations/new.html.erb
<h1>New warehouselocation</h1>

<%= render 'form' %>

<%= link_to 'Back', warehouselocations_path %>

app/views/warehouselocations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Warehousename:</b>
  <%= @warehouselocation.warehousename %>
</p>

<p>
  <b>Street:</b>
  <%= @warehouselocation.street %>
</p>

<p>
  <b>Number:</b>
  <%= @warehouselocation.number %>
</p>

<p>
  <b>Zip:</b>
  <%= @warehouselocation.zip %>
</p>

<p>
  <b>City:</b>
  <%= @warehouselocation.city %>
</p>

<p>
  <b>Country:</b>
  <%= @warehouselocation.country %>
</p>

<p>
  <b>Contactperson:</b>
  <%= @warehouselocation.contactperson %>
</p>

<p>
  <b>Phone:</b>
  <%= @warehouselocation.phone %>
</p>

<p>
  <b>Mobile:</b>
  <%= @warehouselocation.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @warehouselocation.email %>
</p>


<%= link_to 'Edit', edit_warehouselocation_path(@warehouselocation) %> |
<%= link_to 'Back', warehouselocations_path %>